Repository ynput/ayon-traypublisher, pull requests merged in 2025-06, with the labels that each got.

#93 Projects widget: Use ProjectsWidget from ayon-core
  client/ayon_traypublisher/ui/_projects_widget.py
  client/ayon_traypublisher/ui/projects_widget.py
  client/ayon_traypublisher/ui/window.py
Labels: type: enhancement

#95 Settings: Refactor `conditionalEnum` -> `conditional_enum`
  server/settings/editorial_creators.py
Labels: type: enhancement, community

#94 Add default_variants and enabled settings for Texture Creator
  server/settings/creator_plugins.py
Labels: type: enhancement, sponsored
