Repository ynput/ayon-traypublisher, pull requests merged in 2025-03, with the labels that each got.

#75 AY-7442 Add SXR support for plate, render and image simple publishers.
  client/ayon_traypublisher/plugins/publish/collect_simple_instances.py
  client/ayon_traypublisher/plugins/publish/validate_frame_ranges.py
  server/settings/simple_creators.py
Labels: type: enhancement, sponsored

#79 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature

#80 Add spm file as publishing format in tray publisher
  server/settings/simple_creators.py
Labels: sponsored, type: feature
