Repository ynput/ayon-traypublisher, pull requests merged in 2025-02, with the labels that each got.

#66 Chore: Process per project and webactions
  client/ayon_traypublisher/addon.py
  client/ayon_traypublisher/api/main.py
  client/ayon_traypublisher/api/pipeline.py
  client/ayon_traypublisher/csv_publish.py
  client/ayon_traypublisher/ui/__init__.py
  client/ayon_traypublisher/ui/window.py
  server/__init__.py
Labels: type: feature

#67 Ingest CSV: Use create context functions to get entities
  client/ayon_traypublisher/csv_publish.py
Labels: type: enhancement, community

#74 Create colorpsace look: Capture errors on initialization
  client/ayon_traypublisher/plugins/create/create_colorspace_look.py
Labels: type: enhancement

#71 AY-7437 Make create_colorspace_look able to handle multiple chained files.
  client/ayon_traypublisher/plugins/create/create_colorspace_look.py
  client/ayon_traypublisher/plugins/publish/collect_colorspace_look.py
  client/ayon_traypublisher/plugins/publish/validate_colorspace_look.py
Labels: type: enhancement, sponsored

#58 Editorial Advanced Creator
  client/ayon_traypublisher/plugins/create/create_editorial_advanced.py
  client/ayon_traypublisher/plugins/create/create_editorial_simple.py
  client/ayon_traypublisher/plugins/publish/collect_clip_instances.py
  client/ayon_traypublisher/plugins/publish/collect_editorial_instances.py
  package.py
  server/settings/editorial_creators.py
Labels: sponsored, type: feature

#72 Fix publishing multiple representations with common extension (Image).
  client/ayon_traypublisher/plugins/publish/collect_simple_instances.py
Labels: type: bug
